"""Render the paired centering control from its saved summary; no model rerun."""
import csv
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
RESULTS = ROOT / 'code/downstream-evaluation/results/centering-control'
rows = list(csv.DictReader((RESULTS / 'summary.csv').open()))
methods = {
    'naive': 'Naive',
    'gaussian': 'Gaussian SIM',
    'hybrid': 'Hybrid',
    'residual_jumphmm': 'JumpHMM-on-residuals',
    'block_bootstrap': 'Block bootstrap',
    'garch_t': r'GARCH(1,1)-$t$',
}
lookup = {(r['population'], r['method'], r['treatment']): r for r in rows}
assert len(lookup) == 24
for method, label in methods.items():
    native = lookup['common', method, 'native']
    centered = lookup['common', method, 'centered']
    assert int(native['assets']) == int(centered['assets']) == 393
    assert int(native['paths']) == int(centered['paths']) == 39300
    if method in ('naive', 'hybrid'):
        assert all(native[k] == centered[k] for k in native if k != 'treatment')
    # Establish the relationship to the published native comparison, including
    # the available-population denominator for GARCH.
    existing = (ROOT / 'arxiv-paper/sections/tables/table1_aggregate.tex').read_text()
    table_row = next(line for line in existing.splitlines() if line.startswith(label + ' &'))
    cells = table_row.split(' & ')[1:]
    source = lookup['available', method, 'native']
    for i, key, decimals in ((0, 'alpha_error', 3), (1, 'beta_error', 3),
                             (2, 'r2_error', 3), (3, 'ks_pass', 1),
                             (4, 'ad_pass', 1), (5, 'w1', 3), (6, 'kurtosis', 3)):
        assert f'{float(source[key]):.{decimals}f}' == cells[i], (method, key)

lines = [
    '% Generated by audits/2026-09-14-review/centering-correction/render_table.py',
    r'\begin{tabular}{lrrrrrrrr}',
    r'\toprule',
    r' & \multicolumn{2}{c}{KS pass (\%)} & \multicolumn{2}{c}{AD pass (\%)}'
    r' & \multicolumn{2}{c}{$W_1$} & \multicolumn{2}{c}{$|\hat\alpha-\alpha|$} \\',
    r'\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}\cmidrule(lr){8-9}',
    r'Method & Native & Centered & Native & Centered & Native & Centered & Native & Centered \\',
    r'\midrule',
]
for method, label in methods.items():
    values = [label]
    for key, decimals in (('ks_pass', 1), ('ad_pass', 1), ('w1', 3), ('alpha_error', 3)):
        for treatment in ('native', 'centered'):
            values.append(f"{float(lookup['common', method, treatment][key]):.{decimals}f}")
    lines.append(' & '.join(values) + r' \\')
lines.extend([r'\bottomrule', r'\end{tabular}', ''])
table = '\n'.join(lines)
for tree in ('arxiv-paper', 'jfds-paper'):
    (ROOT / tree / 'sections/tables/tableS_centering_control.tex').write_text(table)

checks = {
    'native_values_match_existing_table_at_reported_precision': True,
    'common_population_is_393_for_all_six_methods': True,
    'naive_and_hybrid_control_metrics_identical': True,
    'rendered_tables_identical': True,
    'summary_sha256': hashlib.sha256((RESULTS / 'summary.csv').read_bytes()).hexdigest(),
    'table_sha256': hashlib.sha256(table.encode()).hexdigest(),
}
(Path(__file__).parent / 'table-checks.json').write_text(json.dumps(checks, indent=2) + '\n')
print(json.dumps(checks, indent=2))
